"""empty message

Revision ID: 1580b937feff
Revises: 6c2a4654b01c
Create Date: 2020-02-11 18:16:53.248629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1580b937feff'
down_revision = '6c2a4654b01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('about', sa.String(length=500), nullable=True))
    op.add_column('product', sa.Column('link', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'link')
    op.drop_column('product', 'about')
    # ### end Alembic commands ###
