"""empty message

Revision ID: 6c2a4654b01c
Revises: f533294487fa
Create Date: 2020-02-11 18:16:24.617269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c2a4654b01c'
down_revision = 'f533294487fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'link')
    op.drop_column('product', 'about')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('about', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('product', sa.Column('link', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
