"""empty message

Revision ID: f533294487fa
Revises: 28b382655e74
Create Date: 2020-02-10 19:02:09.919107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f533294487fa'
down_revision = '28b382655e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('link', sa.String(length=100), nullable=False))
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('product', 'link')
    # ### end Alembic commands ###
